package com.application.eventmanagement;

import java.time.LocalDate;

public class Event {
    private int id;
    private String name;
    private LocalDate date;
    private String location;
    private int createdBy;

    // Constructor for new events (no ID, auto-generated by DB)
    public Event(String name, LocalDate date, String location, int createdBy) {
        this.id = 0; // ID will be set by database
        this.name = name;
        this.date = date;
        this.location = location;
        this.createdBy = createdBy;
    }

    // Constructor for retrieving events from DB (with ID)
    public Event(int id, String name, LocalDate date, String location, int createdBy) {
        this.id = id;
        this.name = name;
        this.date = date;
        this.location = location;
        this.createdBy = createdBy;
    }

    // Getters and Setters
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public LocalDate getDate() {
        return date;
    }

    public void setDate(LocalDate date) {
        this.date = date;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public int getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }

    @Override
    public String toString() {
        return "Event{id=" + id + ", name='" + name + "', date=" + date + ", location='" + location + "', createdBy=" + createdBy + "}";
    }
}