package com.application.eventmanagement;

public class Feedback {
    private int id;
    private int eventId;
    private int userId;
    private int rating;
    private String comments;

    // Constructor for new feedback (no ID, auto-generated by DB)
    public Feedback(int eventId, int userId, int rating, String comments) {
        this.id = 0; // ID will be set by database
        this.eventId = eventId;
        this.userId = userId;
        this.rating = rating;
        this.comments = comments;
    }

    // Constructor for retrieving feedback from DB (with ID)
    public Feedback(int id, int eventId, int userId, int rating, String comments) {
        this.id = id;
        this.eventId = eventId;
        this.userId = userId;
        this.rating = rating;
        this.comments = comments;
    }

    // Getters and Setters
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getEventId() {
        return eventId;
    }

    public void setEventId(int eventId) {
        this.eventId = eventId;
    }

    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public int getRating() {
        return rating;
    }

    public void setRating(int rating) {
        this.rating = rating;
    }

    public String getComments() {
        return comments;
    }

    public void setComments(String comments) {
        this.comments = comments;
    }

    @Override
    public String toString() {
        return "Feedback{id=" + id + ", eventId=" + eventId + ", userId=" + userId + ", rating=" + rating + ", comments='" + comments + "'}";
    }
}