package com.application.eventmanagement;

public class User {
    private int id;
    private String username;
    private String email;
    private String password;
    private String role;
    private String program;
    private Integer semester;

    // Constructor for new users (no ID, auto-generated by DB)
    public User(String username, String email, String password, String role, String program, Integer semester) {
        this.id = 0; // ID will be set by database
        this.username = username;
        this.email = email;
        this.password = password;
        this.role = role;
        this.program = program;
        this.semester = semester;
    }

    // Constructor for retrieving users from DB (with ID)
    public User(int id, String username, String email, String password, String role, String program, Integer semester) {
        this.id = id;
        this.username = username;
        this.email = email;
        this.password = password;
        this.role = role;
        this.program = program;
        this.semester = semester;
    }

    // Getters and Setters
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getRole() {
        return role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public String getProgram() {
        return program;
    }

    public void setProgram(String program) {
        this.program = program;
    }

    public Integer getSemester() {
        return semester;
    }

    public void setSemester(Integer semester) {
        this.semester = semester;
    }

    @Override
    public String toString() {
        return "User{id=" + id + ", username='" + username + "', email='" + email + "', role='" + role + "'}";
    }
}