package com.application.eventmanagement;

public class FileMetadata {
    private int id;
    private int eventId;
    private String fileName;
    private String filePath;
    private int uploadedBy;

    // Constructor for new file metadata (no ID, auto-generated by DB)
    public FileMetadata(int eventId, String fileName, String filePath, int uploadedBy) {
        this.id = 0; // ID will be set by database
        this.eventId = eventId;
        this.fileName = fileName;
        this.filePath = filePath;
        this.uploadedBy = uploadedBy;
    }

    // Constructor for retrieving file metadata from DB (with ID)
    public FileMetadata(int id, int eventId, String fileName, String filePath, int uploadedBy) {
        this.id = id;
        this.eventId = eventId;
        this.fileName = fileName;
        this.filePath = filePath;
        this.uploadedBy = uploadedBy;
    }

    // Getters and Setters
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getEventId() {
        return eventId;
    }

    public void setEventId(int eventId) {
        this.eventId = eventId;
    }

    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    public String getFilePath() {
        return filePath;
    }

    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    public int getUploadedBy() {
        return uploadedBy;
    }

    public void setUploadedBy(int uploadedBy) {
        this.uploadedBy = uploadedBy;
    }

    @Override
    public String toString() {
        return "FileMetadata{id=" + id + ", eventId=" + eventId + ", fileName='" + fileName + "', filePath='" + filePath + "', uploadedBy=" + uploadedBy + "}";
    }
}