package com.application.eventmanagement;

import java.sql.SQLException;
import java.time.LocalDate;

public class Registration {
    private int id;
    private int userId;
    private int eventId;
    private LocalDate registrationDate;
    private String program;
    private int semester;

    // Constructor for new registrations (no ID, auto-generated by DB)
    public Registration(int userId, int eventId, LocalDate registrationDate, String program, int semester) {
        this.id = 0; // ID will be set by database
        this.userId = userId;
        this.eventId = eventId;
        this.registrationDate = registrationDate;
        this.program = program;
        this.semester = semester;
    }

    // Constructor accepting User and Event objects with program and semester
    public Registration(User user, Event event, String program, int semester) {
        this.id = 0; // ID will be set by database
        this.userId = user.getId();
        this.eventId = event.getId();
        this.registrationDate = LocalDate.now(); // Use current date for registration
        this.program = program;
        this.semester = semester;
    }

    // Constructor for retrieving registrations from DB (with ID)
    public Registration(int id, int userId, int eventId, LocalDate registrationDate, String program, int semester) {
        this.id = id;
        this.userId = userId;
        this.eventId = eventId;
        this.registrationDate = registrationDate;
        this.program = program;
        this.semester = semester;
    }

    // Getters and Setters
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public int getEventId() {
        return eventId;
    }

    public void setEventId(int eventId) {
        this.eventId = eventId;
    }

    public LocalDate getRegistrationDate() {
        return registrationDate;
    }

    public void setRegistrationDate(LocalDate registrationDate) {
        this.registrationDate = registrationDate;
    }

    public String getProgram() {
        return program;
    }

    public void setProgram(String program) {
        this.program = program;
    }

    public int getSemester() {
        return semester;
    }

    public void setSemester(int semester) {
        this.semester = semester;
    }

    // Derived methods to get User and Event objects
    public User getUser() throws SQLException {
        return DataManager.getInstance().getUser(this.userId);
    }

    public Event getEvent() throws SQLException {
        return DataManager.getInstance().getEvent(this.eventId);
    }

    @Override
    public String toString() {
        return "Registration{id=" + id + ", userId=" + userId + ", eventId=" + eventId + ", registrationDate=" + registrationDate +
                ", program='" + program + "', semester=" + semester + "}";
    }
}